<a href="https://colab.research.google.com/github/Kornel1156/Data-Science/blob/main/2_Pandas_Analiza_Danych/01_biblioteka_pandas_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Spis Treści
# Podstawowe Struktury Danych w Pandas
1. [pd.Series](#scrollTo=Series)
2. [pd.DataFrame](#scrollTo=DataFrame)
2. [Selekcja kolumn](#scrollTo=Selekcja_kolumn)

instalacja biblioteki Pandas

In [30]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Import biblioteki

In [31]:
import pandas as pd
pd.__version__

'2.2.2'

# Series

In [32]:
# tworzymy obiekt za pomoca funkcji Series , który automatycznie przyporzdkowywuje indeksy wierszy oraz kolumn
s = pd.Series([3, 2, 4 , 6 ] )
s

0    3
1    2
2    4
3    6
dtype: int64

In [33]:
# dodanie parametru ktory bedzie przyporzadkowywał wierszom nadane indexy
s = pd.Series([3, 2, 4 , 6 ] , index = ['a', 'b', 'c', 'd' ] )
s

a    3
b    2
c    4
d    6
dtype: int64

In [34]:
# dodanie parametru ktory bedzie przyporzadkowywał wierszom nadane indexy oraz nazwe naszej serii danych
s = pd.Series([3, 2, 4 , 6 ] , index = ['a', 'b', 'c', 'd' ] , name='nazwa_serii_danych' )
s

a    3
b    2
c    4
d    6
Name: nazwa_serii_danych, dtype: int64

In [35]:
# dostosowanie typu danych do podanego jak w numpy wszystkie musza miec ten sam typ danych
# jesli podamy rozne dane to seria przyjmie typ danych object
s = pd.Series([3., 2, 4 , 6 ] , index = ['a', 'b', 'c', 'd' ] )
s

a    3.0
b    2.0
c    4.0
d    6.0
dtype: float64

! ! ! BRAKI DANYCH ! ! !  
jak sobie z nimi poradzić ?
w tym celu wykorzystujemy biblioteke numpy trzeba ja zaimportować

In [36]:
import numpy as np

specjalny atrybut w bibliotece numpy który pozwala na przedstawianie brakujacych danych jako typ np.nan - określa brakujace dane

In [37]:
np.nan

nan

In [38]:
# seria ze wstawionym typem przedstawiajacym brakujaca wartosc danych jako nan
s = pd.Series([3., np.nan, 4 , 6 ] , index = ['a', 'b', 'c', 'd' ] )
# brak wartosc w wierszu b
s

a    3.0
b    NaN
c    4.0
d    6.0
dtype: float64

In [45]:
# obiekt series składający sie z danych typu bool
s = pd.Series(data=[True , False , True ])
s

0     True
1    False
2     True
dtype: bool

In [48]:
# uzywanie danych i dzialanie z binlioteka dla danych czasowych z szeregami czasowymi itd czasem
# generowanie wartosci od 10 do 19 włacznie bez 20 | generujemy daty poczawszy od rok 2020-01-01 | parametr periods czyli ilosc dni od tego dnia
s = pd.Series(data=np.arange(10, 20) , index=pd.date_range(start='20200101' , periods=10))
s

2020-01-01    10
2020-01-02    11
2020-01-03    12
2020-01-04    13
2020-01-05    14
2020-01-06    15
2020-01-07    16
2020-01-08    17
2020-01-09    18
2020-01-10    19
Freq: D, dtype: int64

# DataFrame

# Selekcja kolumn