<a href="https://colab.research.google.com/github/Kornel1156/Data-Science/blob/main/2_Pandas_Analiza_Danych/05_%C5%82aczenie_danych.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Spis treści:
1. [wczytanie Danych](#a1)
2. [Preprocessing](#a2)
3. [konkatenacja danych](#a3)
4. [metoda append()](#a4))

In [ ]:
# import bibliotek
import numpy as np
import pandas as pd

In [ ]:
# sprawdzenie wersji biblioteki pandas
pd.__version__

'2.2.3'

In [ ]:
# sprawdzenie wersji biblioteki numpy
np.__version__

'2.0.2'

### <a name='a1'></a> wczytanie Danych

In [ ]:
# pobranie danych z api finance yahoo
import yfinance as yf

def fetch_financial_data(company='AMZN'):
    """Pobiera dane dotyczące notowań spółki."""
    return yf.download(company)

apple = fetch_financial_data('AAPL')
amazon = fetch_financial_data('AMZN')
google = fetch_financial_data('GOOGL')
uber = fetch_financial_data('UBER')

# spłaszczenie kolumn w yfinance
apple.columns = apple.columns.get_level_values(0)
amazon.columns = amazon.columns.get_level_values(0)
google.columns = google.columns.get_level_values(0)
uber.columns = uber.columns.get_level_values(0)

/tmp/ipykernel_440/1319862041.py:6: FutureWarning: YF.download() has changed argument auto_adjust default to True
  return yf.download(company)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_440/1319862041.py:6: FutureWarning: YF.download() has changed argument auto_adjust default to True
  return yf.download(company)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_440/1319862041.py:6: FutureWarning: YF.download() has changed argument auto_adjust default to True
  return yf.download(company)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_440/1319862041.py:6: FutureWarning: YF.download() has changed argument auto_adjust default to True
  return yf.download(company)
[*********************100%***********************]  1 of 1 completed

In [ ]:
# wyswietlenie danych o notowaniach spółki

# Kazda tabela danych spółek ma inna ilosc wierszy ale łaczy ich index

uber.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 23 entries, 2026-07-20 to 2026-08-19
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   23 non-null     float64
 1   High    23 non-null     float64
 2   Low     23 non-null     float64
 3   Open    23 non-null     float64
 4   Volume  23 non-null     int64
dtypes: float64(4), int64(1)
memory usage: 1.1 KB

In [ ]:
# 5 wierszy apple
apple.head()

Price            Close        High         Low        Open    Volume
Date
2026-07-20  326.308563  333.422423  323.401067  333.222613  53468000
2026-07-21  327.457581  329.315994  321.942348  322.851568  41338900
2026-07-22  325.609192  328.716497  323.061371  327.587466  38755900
2026-07-23  321.382843  323.021414  319.074836  321.452790  40840800
2026-07-24  332.733032  334.081875  321.342861  321.512728  47489400

### <a name='a2'></a> Preprocessing

In [ ]:
# przed polaczeniem danych nalezy przetworzyc nazwy kolumn
# dodanie przedrostka apple przez kazdym rekordem
apple.columns = ['apple_' + col.lower() for col in apple.columns ]
google.columns = ['google_' + col.lower() for col in google.columns ]
amazon.columns = ['amazon_' + col.lower() for col in amazon.columns ]
uber.columns = ['uber_' + col.lower() for col in uber.columns ]

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [ ]:
apple.head()

,apple_apple_apple_apple_close,apple_apple_apple_apple_high,apple_apple_apple_apple_low,apple_apple_apple_apple_open,apple_apple_apple_apple_volume
Date,,,,,
2026-07-20,326.308563,333.422423,323.401067,333.222613,53468000
2026-07-21,327.457581,329.315994,321.942348,322.851568,41338900
2026-07-22,325.609192,328.716497,323.061371,327.587466,38755900
2026-07-23,321.382843,323.021414,319.074836,321.452790,40840800
2026-07-24,332.733032,334.081875,321.342861,321.512728,47489400

### <a name='a3'></a> konkatenacja danych

In [ ]:
# łaczenie danych  , tabele z danymi ktore chcemy połaczyc oraz wzgledem jakiej osi chcemy je łaczyć wybiermay os y
df = pd.concat(objs=[apple,amazon,google,uber] , axis =1)

In [ ]:
# wyłonienie statystyk
df.describe().T

,count,mean,std,min,25%,50%,75%,max
apple_apple_apple_apple_close,23.0,3.171753e+02,1.247343e+01,3.022500e+02,3.070950e+02,3.121408e+02,3.268831e+02,3.397869e+02
apple_apple_apple_apple_high,23.0,3.199599e+02,1.284860e+01,3.056600e+02,3.100613e+02,3.145387e+02,3.313692e+02,3.442731e+02
apple_apple_apple_apple_low,23.0,3.132511e+02,1.237696e+01,2.997415e+02,3.028650e+02,3.089636e+02,3.225019e+02,3.370593e+02
apple_apple_apple_apple_open,23.0,3.164065e+02,1.244529e+01,3.024691e+02,3.065200e+02,3.101300e+02,3.252195e+02,3.397370e+02
apple_apple_apple_apple_volume,23.0,5.090367e+07,2.180554e+07,2.689561e+07,3.955260e+07,4.613990e+07,5.341945e+07,1.324891e+08
amazon_amazon_amazon_close,23.0,2.572013e+02,1.818729e+01,2.266500e+02,2.401750e+02,2.626500e+02,2.722650e+02,2.840200e+02
amazon_amazon_amazon_high,23.0,2.610700e+02,1.834335e+01,2.328200e+02,2.441350e+02,2.657500e+02,2.768950e+02,2.872000e+02
amazon_amazon_amazon_low,23.0,2.548165e+02,1.763728e+01,2.261600e+02,2.372500e+02,2.585800e+02,2.708950e+02,2.780000e+02
amazon_amazon_amazon_open,23.0,2.582376e+02,1.751641e+01,2.293200e+02,2.422650e+02,2.648800e+02,2.730250e+02,2.815900e+02
amazon_amazon_amazon_volume,23.0,4.594113e+07,2.681166e+07,2.032077e+07,3.203295e+07,3.499950e+07,4.503865e+07,1.290548e+08
google_google_google_close,23.0,3.460924e+02,1.477871e+01,3.176900e+02,3.394000e+02,3.442000e+02,3.552150e+02,3.776500e+02
google_google_google_high,23.0,3.511457e+02,1.588966e+01,3.241800e+02,3.436850e+02,3.499400e+02,3.587400e+02,3.844800e+02
google_google_google_low,23.0,3.421139e+02,1.368751e+01,3.149000e+02,3.358100e+02,3.419300e+02,3.516150e+02,3.675000e+02
google_google_google_open,23.0,3.464407e+02,1.552203e+01,3.184200e+02,3.377500e+02,3.463100e+02,3.555350e+02,3.833400e+02
google_google_google_volume,23.0,2.933062e+07,1.271851e+07,1.113704e+07,1.953025e+07,2.750160e+07,3.375615e+07,6.941970e+07
uber_uber_uber_close,23.0,7.258370e+01,3.541012e+00,6.594000e+01,7.036500e+01,7.161000e+01,7.519000e+01,7.899500e+01
uber_uber_uber_high,23.0,7.368100e+01,3.469246e+00,6.834000e+01,7.099000e+01,7.229000e+01,7.736000e+01,7.913000e+01
uber_uber_uber_low,23.0,7.122107e+01,3.384623e+00,6.541000e+01,6.872500e+01,7.114000e+01,7.458000e+01,7.746500e+01
uber_uber_uber_open,23.0,7.238413e+01,3.362070e+00,6.638000e+01,7.003000e+01,7.131000e+01,7.530750e+01,7.820000e+01
uber_uber_uber_volume,23.0,2.002777e+07,9.367577e+06,1.019570e+07,1.309630e+07,1.808490e+07,2.468610e+07,5.013190e+07

In [ ]:
# formatownie danych dla lepszej reprezentacji
pd.set_option('display.float_format' , lambda x: f'{x:.2f}')
df.describe().T

,count,mean,std,min,25%,50%,75%,max
apple_apple_apple_apple_close,23.00,317.18,12.47,302.25,307.10,312.14,326.88,339.79
apple_apple_apple_apple_high,23.00,319.96,12.85,305.66,310.06,314.54,331.37,344.27
apple_apple_apple_apple_low,23.00,313.25,12.38,299.74,302.87,308.96,322.50,337.06
apple_apple_apple_apple_open,23.00,316.41,12.45,302.47,306.52,310.13,325.22,339.74
apple_apple_apple_apple_volume,23.00,50903670.04,21805540.28,26895611.00,39552600.00,46139900.00,53419450.00,132489100.00
amazon_amazon_amazon_close,23.00,257.20,18.19,226.65,240.18,262.65,272.26,284.02
amazon_amazon_amazon_high,23.00,261.07,18.34,232.82,244.14,265.75,276.90,287.20
amazon_amazon_amazon_low,23.00,254.82,17.64,226.16,237.25,258.58,270.90,278.00
amazon_amazon_amazon_open,23.00,258.24,17.52,229.32,242.26,264.88,273.02,281.59
amazon_amazon_amazon_volume,23.00,45941133.39,26811655.83,20320768.00,32032950.00,34999500.00,45038650.00,129054800.00
google_google_google_close,23.00,346.09,14.78,317.69,339.40,344.20,355.21,377.65
google_google_google_high,23.00,351.15,15.89,324.18,343.68,349.94,358.74,384.48
google_google_google_low,23.00,342.11,13.69,314.90,335.81,341.93,351.61,367.50
google_google_google_open,23.00,346.44,15.52,318.42,337.75,346.31,355.54,383.34
google_google_google_volume,23.00,29330619.26,12718509.23,11137043.00,19530250.00,27501600.00,33756150.00,69419700.00
uber_uber_uber_close,23.00,72.58,3.54,65.94,70.37,71.61,75.19,79.00
uber_uber_uber_high,23.00,73.68,3.47,68.34,70.99,72.29,77.36,79.13
uber_uber_uber_low,23.00,71.22,3.38,65.41,68.73,71.14,74.58,77.46
uber_uber_uber_open,23.00,72.38,3.36,66.38,70.03,71.31,75.31,78.20
uber_uber_uber_volume,23.00,20027769.39,9367576.53,10195700.00,13096300.00,18084900.00,24686100.00,50131900.00

In [ ]:
# wspołczynnik korelacji poszczegolnych zmiennych
# wspołczynnik korelacji - Współczynnik korelacji mówi, jak silnie dwie rzeczy poruszają się względem siebie.
df.corr()

,apple_apple_apple_apple_close,apple_apple_apple_apple_high,apple_apple_apple_apple_low,apple_apple_apple_apple_open,apple_apple_apple_apple_volume,amazon_amazon_amazon_close,amazon_amazon_amazon_high,amazon_amazon_amazon_low,amazon_amazon_amazon_open,amazon_amazon_amazon_volume,google_google_google_close,google_google_google_high,google_google_google_low,google_google_google_open,google_google_google_volume,uber_uber_uber_close,uber_uber_uber_high,uber_uber_uber_low,uber_uber_uber_open,uber_uber_uber_volume
apple_apple_apple_apple_close,1.00,0.99,0.98,0.95,0.01,-0.90,-0.91,-0.91,-0.92,-0.04,-0.61,-0.57,-0.62,-0.61,0.12,-0.59,-0.62,-0.66,-0.64,-0.03
apple_apple_apple_apple_high,0.99,1.00,0.98,0.97,0.02,-0.88,-0.88,-0.89,-0.90,-0.04,-0.57,-0.53,-0.58,-0.58,0.12,-0.57,-0.60,-0.63,-0.63,-0.09
apple_apple_apple_apple_low,0.98,0.98,1.00,0.98,-0.07,-0.90,-0.90,-0.90,-0.91,-0.10,-0.61,-0.57,-0.61,-0.59,0.10,-0.52,-0.56,-0.58,-0.59,-0.06
apple_apple_apple_apple_open,0.95,0.97,0.98,1.00,-0.01,-0.86,-0.86,-0.87,-0.87,-0.05,-0.55,-0.50,-0.55,-0.53,0.13,-0.52,-0.57,-0.57,-0.58,-0.09
apple_apple_apple_apple_volume,0.01,0.02,-0.07,-0.01,1.00,0.09,0.08,0.01,-0.02,0.92,0.28,0.21,0.06,-0.01,0.40,-0.37,-0.46,-0.31,-0.38,-0.17
amazon_amazon_amazon_close,-0.90,-0.88,-0.90,-0.86,0.09,1.00,0.99,0.99,0.98,0.11,0.84,0.80,0.84,0.80,-0.18,0.53,0.47,0.52,0.43,0.16
amazon_amazon_amazon_high,-0.91,-0.88,-0.90,-0.86,0.08,0.99,1.00,0.99,0.99,0.10,0.83,0.82,0.84,0.83,-0.15,0.51,0.45,0.50,0.42,0.21
amazon_amazon_amazon_low,-0.91,-0.89,-0.90,-0.87,0.01,0.99,0.99,1.00,0.99,0.02,0.82,0.80,0.85,0.82,-0.21,0.54,0.50,0.53,0.46,0.19
amazon_amazon_amazon_open,-0.92,-0.90,-0.91,-0.87,-0.02,0.98,0.99,0.99,1.00,-0.00,0.79,0.79,0.82,0.83,-0.17,0.52,0.49,0.53,0.47,0.25
amazon_amazon_amazon_volume,-0.04,-0.04,-0.10,-0.05,0.92,0.11,0.10,0.02,-0.00,1.00,0.26,0.20,0.06,0.02,0.46,-0.32,-0.43,-0.27,-0.32,-0.19
google_google_google_close,-0.61,-0.57,-0.61,-0.55,0.28,0.84,0.83,0.82,0.79,0.26,1.00,0.96,0.96,0.89,-0.12,0.27,0.14,0.27,0.12,0.09
google_google_google_high,-0.57,-0.53,-0.57,-0.50,0.21,0.80,0.82,0.80,0.79,0.20,0.96,1.00,0.94,0.96,0.01,0.18,0.06,0.18,0.07,0.25
google_google_google_low,-0.62,-0.58,-0.61,-0.55,0.06,0.84,0.84,0.85,0.82,0.06,0.96,0.94,1.00,0.94,-0.23,0.35,0.25,0.35,0.22,0.12
google_google_google_open,-0.61,-0.58,-0.59,-0.53,-0.01,0.80,0.83,0.82,0.83,0.02,0.89,0.96,0.94,1.00,-0.08,0.27,0.18,0.27,0.18,0.33
google_google_google_volume,0.12,0.12,0.10,0.13,0.40,-0.18,-0.15,-0.21,-0.17,0.46,-0.12,0.01,-0.23,-0.08,1.00,-0.63,-0.62,-0.53,-0.50,0.26
uber_uber_uber_close,-0.59,-0.57,-0.52,-0.52,-0.37,0.53,0.51,0.54,0.52,-0.32,0.27,0.18,0.35,0.27,-0.63,1.00,0.95,0.94,0.85,-0.33
uber_uber_uber_high,-0.62,-0.60,-0.56,-0.57,-0.46,0.47,0.45,0.50,0.49,-0.43,0.14,0.06,0.25,0.18,-0.62,0.95,1.00,0.95,0.94,-0.30
uber_uber_uber_low,-0.66,-0.63,-0.58,-0.57,-0.31,0.52,0.50,0.53,0.53,-0.27,0.27,0.18,0.35,0.27,-0.53,0.94,0.95,1.00,0.95,-0.43
uber_uber_uber_open,-0.64,-0.63,-0.59,-0.58,-0.38,0.43,0.42,0.46,0.47,-0.32,0.12,0.07,0.22,0.18,-0.50,0.85,0.94,0.95,1.00,-0.38
uber_uber_uber_volume,-0.03,-0.09,-0.06,-0.09,-0.17,0.16,0.21,0.19,0.25,-0.19,0.09,0.25,0.12,0.33,0.26,-0.33,-0.30,-0.43,-0.38,1.00

In [ ]:
# przedstawienie wszystkich dostepnych kolumn
df.columns

Index(['apple_apple_apple_apple_close', 'apple_apple_apple_apple_high',
       'apple_apple_apple_apple_low', 'apple_apple_apple_apple_open',
       'apple_apple_apple_apple_volume', 'amazon_amazon_amazon_close',
       'amazon_amazon_amazon_high', 'amazon_amazon_amazon_low',
       'amazon_amazon_amazon_open', 'amazon_amazon_amazon_volume',
       'google_google_google_close', 'google_google_google_high',
       'google_google_google_low', 'google_google_google_open',
       'google_google_google_volume', 'uber_uber_uber_close',
       'uber_uber_uber_high', 'uber_uber_uber_low', 'uber_uber_uber_open',
       'uber_uber_uber_volume'],
      dtype='object')

In [ ]:
# policznie wspolcznika korealcji tylko dla wybranych np kolumn albo wycinka danych

# ceny zamkniecia - czyli rekordy dla danej kolumn ktorej nazwa konczy sie na close
closes = [col for col in df.columns if col.endswith('close')]
closes

['apple_apple_apple_apple_close',
 'amazon_amazon_amazon_close',
 'google_google_google_close',
 'uber_uber_uber_close']

In [ ]:
# wycinamy obiekt dataFrame ktora reprezentuje kolumny z cena zamkniecia

# ! ! !  UWAGA ! ! !
# dataframe - to obiekt ktory jest tabela ma wiersze i kolumny
# series - to obiekt ktory ma jedna kolumne'

print(df[closes])
print(type(df[closes]))

/bin/bash: line 1: UWAGA: command not found
            apple_apple_apple_apple_close  amazon_amazon_amazon_close  \
Date
2026-07-20                         326.31                      249.99
2026-07-21                         327.46                      247.55
2026-07-22                         325.61                      244.85
2026-07-23                         321.38                      233.66
2026-07-24                         332.73                      232.11
2026-07-27                         336.62                      231.39
2026-07-28                         339.79                      230.86
2026-07-29                         337.90                      226.65
2026-07-30                         333.14                      235.50
2026-07-31                         308.64                      271.58
2026-08-03                         303.16                      284.02
2026-08-04                         309.11                      277.42
2026-08-05                         310.73                      272.65
2026-08-06                         312.14                      272.26
2026-08-07                         313.06                      274.48
2026-08-10                         308.26                      278.09
2026-08-11                         304.91                      272.27
2026-08-12                         302.25                      267.28
2026-08-13                         305.26                      265.13
2026-08-14                         305.93                      262.65
2026-08-17                         305.59                      261.31
2026-08-18                         310.03                      259.45
2026-08-19                         315.02                      264.48

            google_google_google_close  uber_uber_uber_close
Date
2026-07-20                      351.99                 72.17
2026-07-21                      347.15                 71.55
2026-07-22                      342.09                 70.33
2026-07-23                      317.69                 68.91
2026-07-24                      319.74                 65.94
2026-07-27                      326.56                 68.18
2026-07-28                      333.71                 70.74
2026-07-29                      336.71                 71.20
2026-07-30                      333.66                 70.37
2026-07-31                      356.13                 70.36
2026-08-03                      373.51                 71.61
2026-08-04                      377.65                 71.99
2026-08-05                      362.43                 68.18
2026-08-06                      357.75                 70.47
2026-08-07                      354.30                 75.02
2026-08-10                      357.52                 78.03
2026-08-11                      343.80                 78.54
2026-08-12                      343.54                 75.36
2026-08-13                      346.36                 75.88
2026-08-14                      345.90                 75.95
2026-08-17                      344.00                 74.99
2026-08-18                      344.20                 74.66
2026-08-19                      343.73                 79.00
<class 'pandas.core.frame.DataFrame'>

In [ ]:
# liczymy korelacje zmiennych
df[closes].corr()

,apple_apple_apple_apple_close,amazon_amazon_amazon_close,google_google_google_close,uber_uber_uber_close
apple_apple_apple_apple_close,1.00,-0.90,-0.61,-0.59
amazon_amazon_amazon_close,-0.90,1.00,0.84,0.53
google_google_google_close,-0.61,0.84,1.00,0.27
uber_uber_uber_close,-0.59,0.53,0.27,1.00

In [ ]:
# wolumen obrotu
closes = [col for col in df.columns if col.endswith('close') or col.endswith('volume') ]
closes

['apple_apple_apple_apple_close',
 'apple_apple_apple_apple_volume',
 'amazon_amazon_amazon_close',
 'amazon_amazon_amazon_volume',
 'google_google_google_close',
 'google_google_google_volume',
 'uber_uber_uber_close',
 'uber_uber_uber_volume']

In [ ]:
# wspołczynnik korelacji poszczegolnych zmiennych
# wspołczynnik korelacji - Współczynnik korelacji mówi, jak silnie dwie rzeczy poruszają się względem siebie.
df[closes].corr()

,apple_apple_apple_apple_close,apple_apple_apple_apple_volume,amazon_amazon_amazon_close,amazon_amazon_amazon_volume,google_google_google_close,google_google_google_volume,uber_uber_uber_close,uber_uber_uber_volume
apple_apple_apple_apple_close,1.00,0.01,-0.90,-0.04,-0.61,0.12,-0.59,-0.03
apple_apple_apple_apple_volume,0.01,1.00,0.09,0.92,0.28,0.40,-0.37,-0.17
amazon_amazon_amazon_close,-0.90,0.09,1.00,0.11,0.84,-0.18,0.53,0.16
amazon_amazon_amazon_volume,-0.04,0.92,0.11,1.00,0.26,0.46,-0.32,-0.19
google_google_google_close,-0.61,0.28,0.84,0.26,1.00,-0.12,0.27,0.09
google_google_google_volume,0.12,0.40,-0.18,0.46,-0.12,1.00,-0.63,0.26
uber_uber_uber_close,-0.59,-0.37,0.53,-0.32,0.27,-0.63,1.00,-0.33
uber_uber_uber_volume,-0.03,-0.17,0.16,-0.19,0.09,0.26,-0.33,1.00

### <a name='a4'></a> metoda append()